namespace HlaX64.Cli.CodeGen;

using HlaX64.Compiler.Ast;
using HlaX64.Compiler.Lexing;
using HlaX64.Compiler.Parsing;

public static class InteropGenerator
{
    public static string GenerateCHeader(string source, string libraryName)
    {
        var program = ParseSource(source);
        var sb = new System.Text.StringBuilder();
        var guard = libraryName.ToUpperInvariant().Replace(".", "_").Replace("-", "_") + "_H";

        sb.AppendLine("// Generated by HlaX64");
        sb.AppendLine($"#ifndef {guard}");
        sb.AppendLine($"#define {guard}");
        sb.AppendLine("#include <stdint.h>");
        sb.AppendLine();

        foreach (var proc in GetExportProcs(program))
        {
            var retType = CType(proc.ReturnsRegister is not null ? "int64" : "void");
            sb.Append($"{retType} {proc.Name}(");
            for (int i = 0; i < proc.Parameters.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append($"{CType(proc.Parameters[i].Type)} {proc.Parameters[i].Name}");
            }
            sb.AppendLine(");");
        }

        sb.AppendLine();
        sb.AppendLine("#endif");
        return sb.ToString();
    }

    public static string GeneratePInvoke(string source, string libraryName)
    {
        var program = ParseSource(source);
        var sb = new System.Text.StringBuilder();

        sb.AppendLine("// Generated by HlaX64");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class HlaX64Interop");
        sb.AppendLine("{");

        foreach (var proc in GetExportProcs(program))
        {
            var retType = CsType(proc.ReturnsRegister is not null ? "int64" : "void");
            sb.AppendLine($"    [LibraryImport(\"{libraryName}\")]");
            sb.Append($"    internal static partial {retType} {proc.Name}(");
            for (int i = 0; i < proc.Parameters.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                var p = proc.Parameters[i];
                sb.Append($"{CsType(p.Type)} {p.Name}");
            }
            sb.AppendLine(");");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static ProgramNode ParseSource(string source)
    {
        var lexer = new Lexer(source);
        var tokens = lexer.Tokenize();
        var parser = new Parser(tokens);
        return parser.Parse();
    }

    private static IEnumerable<ProcedureNode> GetExportProcs(ProgramNode program)
    {
        return program.Statements.OfType<ProcedureNode>().Where(p => p.IsExport);
    }

    private static string CType(string hlaType)
    {
        return hlaType.ToLowerInvariant() switch
        {
            "int8" => "int8_t",
            "int16" => "int16_t",
            "int32" => "int32_t",
            "int64" => "int64_t",
            "uint8" or "byte" => "uint8_t",
            "uint16" or "word" => "uint16_t",
            "uint32" or "dword" => "uint32_t",
            "uint64" or "qword" => "uint64_t",
            "ptr" => "void*",
            _ => "int64_t"
        };
    }

    private static string CsType(string hlaType)
    {
        return hlaType.ToLowerInvariant() switch
        {
            "int8" => "sbyte",
            "int16" => "short",
            "int32" => "int",
            "int64" => "long",
            "uint8" or "byte" => "byte",
            "uint16" or "word" => "ushort",
            "uint32" or "dword" => "uint",
            "uint64" or "qword" => "ulong",
            "ptr" => "nint",
            _ => "long"
        };
    }
}
