// Generated by HlaX64 — regenerate with:
// hla64 generate-pinvoke native_count_lines.hla64 -l native_count_lines -o caller/HlaX64Interop.cs
using System.Runtime.InteropServices;

internal static partial class HlaX64Interop
{
    [LibraryImport("native_count_lines")]
    internal static partial long CountLines(nint data, long length);
}
