# Generate euler008 with embedded 1000-digit PE string
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$dataFile = Join-Path $root 'examples/project-euler/data/euler008-digits.txt'
$digits = (Get-Content -Raw $dataFile).Trim() -replace '\s',''

if ($digits.Length -ne 1000) { throw "Expected 1000 digits, got $($digits.Length)" }

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// euler008-largest-product-series.hla64 — PE #8 (23514624000)')
[void]$sb.AppendLine('// Generated by scripts/generate-euler008.ps1')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('program euler008;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('#include("stdlib64.hhf")')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('static')
[void]$sb.AppendLine('    digits: int64[1000];')
[void]$sb.AppendLine('endstatic;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('begin euler008;')

for ($i = 0; $i -lt 1000; $i++) {
    $d = [int][string]$digits[$i]
    [void]$sb.AppendLine("    mov($d, digits[$i]);")
}

[void]$sb.AppendLine('')
[void]$sb.AppendLine('    mov(0, r12);')
[void]$sb.AppendLine('    mov(0, r13);')
[void]$sb.AppendLine('    mov(988, rbx);')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    while(r13 < rbx) do')
[void]$sb.AppendLine('        mov(1, r14);')
[void]$sb.AppendLine('        mov(0, r10);')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('        while(r10 < 13) do')
[void]$sb.AppendLine('            mov(r13, r11);')
[void]$sb.AppendLine('            add(r10, r11);')
[void]$sb.AppendLine('            mov(digits[r11], rax);')
[void]$sb.AppendLine('            imul(rax, r14);')
[void]$sb.AppendLine('            add(1, r10);')
[void]$sb.AppendLine('        endwhile;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('        if(r14 > r12) then')
[void]$sb.AppendLine('            mov(r14, r12);')
[void]$sb.AppendLine('        endif;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('        add(1, r13);')
[void]$sb.AppendLine('    endwhile;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    stdout.put("Euler #8 = ", r12, nl);')
[void]$sb.AppendLine('end euler008;')
[void]$sb.AppendLine('')

$out = Join-Path $root 'examples/project-euler/problems/euler008-largest-product-series.hla64'
Set-Content -Path $out -Value $sb.ToString() -Encoding utf8
Write-Host "Wrote $out"
