# Generate euler011 from data/euler011-matrix.txt
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$dataFile = Join-Path $root 'examples/20-project-euler/data/euler011-matrix.txt'
$lines = Get-Content $dataFile | Where-Object { $_.Trim() -ne '' }
$values = @()
foreach ($line in $lines) {
    foreach ($tok in $line.Trim().Split(' ', [StringSplitOptions]::RemoveEmptyEntries)) {
        $values += [int]$tok
    }
}
if ($values.Count -ne 400) { throw "Expected 400 cells, got $($values.Count)" }

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// euler011-largest-product-grid.hla64 — PE #11 (70600674)')
[void]$sb.AppendLine('// Generated by scripts/generate-euler011.ps1')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('program euler011;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('#include("stdlib64.hhf")')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('static')
[void]$sb.AppendLine('    grid: int64[400];')
[void]$sb.AppendLine('endstatic;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('begin euler011;')
for ($i = 0; $i -lt 400; $i++) {
    [void]$sb.AppendLine("    mov($($values[$i]), grid[$i]);")
}
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    mov(0, r12);')
[void]$sb.AppendLine('    mov(0, r13);')
[void]$sb.AppendLine('    mov(20, rbx);')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    while(r13 < rbx) do')
[void]$sb.AppendLine('        mov(0, r14);')
[void]$sb.AppendLine('        while(r14 < rbx) do')
[void]$sb.AppendLine('            mov(0, r10);')
[void]$sb.AppendLine('            while(r10 < 4) do')
[void]$sb.AppendLine('                mov(1, r15);')
[void]$sb.AppendLine('                mov(1, r11);')
[void]$sb.AppendLine('                while(r11 < 5) do')
[void]$sb.AppendLine('                    mov(r14, r9);')
[void]$sb.AppendLine('                    mov(r13, r8);')
[void]$sb.AppendLine('                    mov(r11, rax);')
[void]$sb.AppendLine('                    sub(1, rax);')
[void]$sb.AppendLine('                    if(r10 = 0) then add(rax, r9); endif;')
[void]$sb.AppendLine('                    if(r10 = 1) then add(rax, r8); endif;')
[void]$sb.AppendLine('                    if(r10 = 2) then add(rax, r9); add(rax, r8); endif;')
[void]$sb.AppendLine('                    if(r10 = 3) then add(rax, r9); mov(r8, rax); sub(r11, rax); add(1, rax); mov(rax, r8); endif;')
[void]$sb.AppendLine('                    if(r9 < 0) then mov(100, r11); endif;')
[void]$sb.AppendLine('                    if(r9 > 19) then mov(100, r11); endif;')
[void]$sb.AppendLine('                    if(r8 < 0) then mov(100, r11); endif;')
[void]$sb.AppendLine('                    if(r8 > 19) then mov(100, r11); endif;')
[void]$sb.AppendLine('                    mov(r8, rax);')
[void]$sb.AppendLine('                    mov(20, r9);')
[void]$sb.AppendLine('                    imul(r9, rax);')
[void]$sb.AppendLine('                    add(r14, rax);')
[void]$sb.AppendLine('                    mov(r14, r9);')
[void]$sb.AppendLine('                    add(r11, r9);')
[void]$sb.AppendLine('                    sub(1, r9);')
[void]$sb.AppendLine('                    mov(r9, rax);')
[void]$sb.AppendLine('                    mov(grid[rax], rax);')
[void]$sb.AppendLine('                    imul(rax, r15);')
[void]$sb.AppendLine('                    add(1, r11);')
[void]$sb.AppendLine('                endwhile;')
[void]$sb.AppendLine('                if(r11 = 5) then')
[void]$sb.AppendLine('                    if(r15 > r12) then mov(r15, r12); endif;')
[void]$sb.AppendLine('                endif;')
[void]$sb.AppendLine('                add(1, r10);')
[void]$sb.AppendLine('            endwhile;')
[void]$sb.AppendLine('            add(1, r14);')
[void]$sb.AppendLine('        endwhile;')
[void]$sb.AppendLine('        add(1, r13);')
[void]$sb.AppendLine('    endwhile;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    stdout.put("Euler #11 = ", r12, nl);')
[void]$sb.AppendLine('end euler011;')
[void]$sb.AppendLine('')

$out = Join-Path $root 'examples/20-project-euler/problems/euler011-largest-product-grid.hla64'
Set-Content -Path $out -Value $sb.ToString() -Encoding utf8
Write-Host "Wrote $out"
