#!/usr/bin/env python3
"""Download (if needed) and generate euler013-large-sum.hla64 with embedded digits."""
from __future__ import annotations

import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "examples/project-euler/data/euler013-numbers.txt"
OUT = ROOT / "examples/project-euler/problems/euler013-large-sum.hla64"
NAYUKI = "https://raw.githubusercontent.com/nayuki/Project-Euler-solutions/master/haskell/p013.hs"
NUM_COUNT = 100
DIGITS_PER = 50


def ensure_data() -> list[str]:
    if not DATA.exists():
        DATA.parent.mkdir(parents=True, exist_ok=True)
        text = urllib.request.urlopen(NAYUKI, timeout=30).read().decode()
        nums = re.findall(r"\b(\d{50})\b", text)
        if len(nums) != NUM_COUNT:
            raise SystemExit(f"Expected {NUM_COUNT} numbers, got {len(nums)}")
        DATA.write_text("\n".join(nums) + "\n", encoding="utf-8")
        print(f"Downloaded {DATA}")

    lines = [ln.strip() for ln in DATA.read_text(encoding="utf-8").splitlines() if ln.strip()]
    if len(lines) != NUM_COUNT:
        raise SystemExit(f"Expected {NUM_COUNT} lines in {DATA}, got {len(lines)}")
    for i, ln in enumerate(lines):
        if len(ln) != DIGITS_PER or not ln.isdigit():
            raise SystemExit(f"Line {i + 1}: expected {DIGITS_PER} digits, got {len(ln)}")
    first10 = str(sum(int(ln) for ln in lines))[:10]
    if first10 != "5537376230":
        raise SystemExit(f"Checksum failed: first 10 digits = {first10}")
    return lines


def main() -> None:
    numbers = ensure_data()

    out: list[str] = [
        "// euler013-large-sum.hla64 — PE #13 (5537376230)",
        "// Generated by scripts/generate_euler013.py",
        "",
        "program euler013;",
        "",
        '#include("stdlib64.hhf")',
        "",
        "static",
        f"    nums: int64[{NUM_COUNT * DIGITS_PER}];",
        "    sum: int64[55];",
        "endstatic;",
        "",
        "begin euler013;",
    ]

    for ni, num in enumerate(numbers):
        base = ni * DIGITS_PER
        for di, ch in enumerate(reversed(num)):
            out.append(f"    mov({ch}, nums[{base + di}]);")

    out += [
        "",
        "    mov(0, r12);",
        "    mov(100, rbx);",
        "",
        "    while(r12 < rbx) do",
        "        mov(0, r9);",
        "        mov(0, r14);",
        "        mov(50, r8);",
        "",
        "        while(r14 < r8) do",
        "            mov(r12, r11);",
        "            mov(50, r10);",
        "            imul(r10, r11);",
        "            add(r14, r11);",
        "            mov(r14, r13);",
        "            mov(nums[r11], rax);",
        "            mov(sum[r13], r10);",
        "            add(r10, rax);",
        "            add(r9, rax);",
        "            mov(rax, r10);",
        "            mov(10, r15);",
        "            mod(r15, rax);",
        "            mov(rax, sum[r13]);",
        "            mov(r10, rax);",
        "            mov(10, r15);",
        "            idiv(r15, rax);",
        "            mov(rax, r9);",
        "            add(1, r14);",
        "            mov(50, r8);",
        "        endwhile;",
        "",
        "        mov(50, r14);",
        "        mov(55, r8);",
        "",
        "        while(r14 < r8) do",
        "            if(r9 = 0) then",
        "                mov(55, r14);",
        "            else",
        "                mov(r14, r13);",
        "                mov(sum[r13], r10);",
        "                add(r9, r10);",
        "                mov(r10, rax);",
        "                mov(10, r15);",
        "                mod(r15, rax);",
        "                mov(rax, sum[r13]);",
        "                mov(r10, rax);",
        "                mov(10, r15);",
        "                idiv(r15, rax);",
        "                mov(rax, r9);",
        "                add(1, r14);",
        "            endif;",
        "        endwhile;",
        "",
        "        add(1, r12);",
        "    endwhile;",
        "",
        "    mov(54, r14);",
        "    mov(1, r15);",
        "",
        "    while(r15 > 0) do",
        "        mov(r14, r11);",
        "        mov(sum[r11], rax);",
        "        if(rax = 0) then",
        "            if(r14 = 0) then",
        "                mov(0, r15);",
        "            else",
        "                sub(1, r14);",
        "            endif;",
        "        else",
        "            mov(0, r15);",
        "        endif;",
        "    endwhile;",
        "",
        "    mov(0, r13);",
        "    mov(0, r12);",
        "    mov(10, r8);",
        "",
        "    while(r12 < r8) do",
        "        mov(r14, r11);",
        "        mov(sum[r11], r10);",
        "        mov(r13, rax);",
        "        mov(10, r11);",
        "        imul(r11, rax);",
        "        add(r10, rax);",
        "        mov(rax, r13);",
        "        sub(1, r14);",
        "        add(1, r12);",
        "    endwhile;",
        "",
        '    stdout.put("Euler #13 = ", r13, nl);',
        "end euler013;",
        "",
    ]

    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
