#!/usr/bin/env python3
"""Download (if needed) and generate euler022-names-scores.hla64 with embedded scores."""
from __future__ import annotations

import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "examples/project-euler/data/euler022-names.txt"
OUT = ROOT / "examples/project-euler/problems/euler022-names-scores.hla64"
URL = "https://projecteuler.net/project/resources/p022_names.txt"
EXPECTED = 871198282


def letter_score(name: str) -> int:
    return sum(ord(c) - 64 for c in name)


def ensure_data() -> list[int]:
    if not DATA.exists():
        DATA.parent.mkdir(parents=True, exist_ok=True)
        DATA.write_bytes(urllib.request.urlopen(URL, timeout=30).read())
        print(f"Downloaded {DATA}")

    text = DATA.read_text(encoding="utf-8")
    names = re.findall(r'"([A-Z]+)"', text)
    if not names:
        raise SystemExit(f"No names parsed from {DATA}")

    names.sort()
    scores = [letter_score(n) for n in names]
    total = sum((i + 1) * s for i, s in enumerate(scores))
    if total != EXPECTED:
        raise SystemExit(f"Checksum failed: total={total}, expected {EXPECTED}")
    return scores


def main() -> None:
    scores = ensure_data()
    n = len(scores)

    out: list[str] = [
        "// euler022-names-scores.hla64 — PE #22 (871198282)",
        "// Generated by scripts/generate_euler022.py",
        "",
        "program euler022;",
        "",
        '#include("stdlib64.hhf")',
        "",
        "static",
        f"    scores: int64[{n}];",
        "endstatic;",
        "",
        "begin euler022;",
    ]

    for i, s in enumerate(scores):
        out.append(f"    mov({s}, scores[{i}]);")

    out += [
        "",
        "    mov(0, r12);",
        "    mov(0, r13);",
        "    mov(1, r14);",
        f"    mov({n}, r11);",
        "",
        "    while(r13 < r11) do",
        "        mov(r13, r15);",
        "        mov(scores[r15], r10);",
        "        mov(r10, rax);",
        "        mov(r14, r10);",
        "        imul(r10, rax);",
        "        add(rax, r12);",
        "        add(1, r13);",
        "        add(1, r14);",
        "    endwhile;",
        "",
        '    stdout.put("Euler #22 = ", r12, nl);',
        "end euler022;",
        "",
    ]

    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUT} ({n} names, total={EXPECTED})")


if __name__ == "__main__":
    main()
