#!/usr/bin/env python3
"""Generate euler018-maximum-path-sum.hla64 with bottom-up DP."""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
data = root / "examples/project-euler/data/euler018-triangle.txt"
out = root / "examples/project-euler/problems/euler018-maximum-path-sum.hla64"

vals: list[int] = []
for line in data.read_text().splitlines():
    line = line.strip()
    if line:
        vals.extend(int(x) for x in line.split())
assert len(vals) == 120

lines = [
    "// euler018-maximum-path-sum.hla64 — PE #18 (1074)",
    "// Generated by scripts/generate_euler018.py",
    "",
    "program euler018;",
    "",
    '#include("stdlib64.hhf")',
    "",
    "static",
    "    tri: int64[120];",
    "    best: int64[120];",
    "endstatic;",
    "",
    "begin euler018;",
]
for i, v in enumerate(vals):
    lines.append(f"    mov({v}, tri[{i}]);")

lines += [
    "",
    "    mov(105, r12);",
    "    mov(120, rbx);",
    "    while(r12 < rbx) do",
    "        mov(tri[r12], rax);",
    "        mov(rax, best[r12]);",
    "        add(1, r12);",
    "    endwhile;",
    "",
    "    mov(13, r12);",
    "    mov(1000, r15);",
    "    while(r15 > 0) do",
    "        mov(r12, rax);",
    "        mov(r12, r10);",
    "        add(1, r10);",
    "        imul(r10, rax);",
    "        mov(2, r10);",
    "        idiv(r10, rax);",
    "        mov(rax, r13);",
    "",
    "        mov(0, r14);",
    "        mov(r12, r11);",
    "        add(1, r11);",
    "        while(r14 < r11) do",
    "            mov(r13, r10);",
    "            add(r14, r10);",
    "            mov(tri[r10], rax);",
    "",
    "            mov(r12, r10);",
    "            add(1, r10);",
    "            mov(r10, r11);",
    "            add(1, r11);",
    "            imul(r11, r10);",
    "            mov(2, r11);",
    "            mov(r10, rax);",
    "            idiv(r11, rax);",
    "            add(r14, rax);",
    "            mov(rax, r10);",
    "            mov(best[r10], r11);",
    "",
    "            mov(r12, r10);",
    "            add(1, r10);",
    "            mov(r10, r11);",
    "            add(1, r11);",
    "            imul(r11, r10);",
    "            mov(2, r11);",
    "            mov(r10, rax);",
    "            idiv(r11, rax);",
    "            add(r14, rax);",
    "            add(1, rax);",
    "            mov(rax, r10);",
    "            mov(best[r10], r10);",
    "",
    "            if(r11 > r10) then mov(r11, r10); endif;",
    "            add(r10, rax);",
    "",
    "            mov(r13, r10);",
    "            add(r14, r10);",
    "            mov(rax, best[r10]);",
    "            add(1, r14);",
    "        endwhile;",
    "",
    "        if(r12 = 0) then",
    "            mov(0, r15);",
    "        else",
    "            sub(1, r12);",
    "        endif;",
    "    endwhile;",
    "",
    '    stdout.put("Euler #18 = ", best[0], nl);',
    "end euler018;",
    "",
]

out.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {out}")
