// Generated by HlaX64
using System.Runtime.InteropServices;

internal static partial class HlaX64Interop
{
    [LibraryImport("native_fnv1a")]
    internal static partial long Fnv1a64(nint data, long length);
}
